trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'bratvaa'
  imageName: 'myapp'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'pipeline'  # Use service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging into Azure..."
        az acr login --name $(acrName)

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags: '$(Build.BuildId)'
      repository: '$(imageName)'

  - task: Docker@2
    displayName: 'Push Docker Image to ACR'
    inputs:
      command: 'push'
      containerRegistry: 'pipeline'  # Use service connection name, NOT ACR name
      repository: '$(imageName)'
      tags: '$(Build.BuildId)'
