trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'bratvaa'
  imageName: 'myapp'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging into Azure..."
        az acr login --name $(acrName)

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      buildContext: '.'
      tags: '$(acrName).azurecr.io/$(imageName):$(Build.BuildId)'

  - task: Docker@2
    displayName: 'Push Docker Image to ACR'
    inputs:
      command: 'push'
      containerRegistry: '$(acrName)'
      repository: '$(imageName)'
      tags: '$(Build.BuildId)'
